<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Bronnoysund.Lookup.Application\Bronnoysund.Lookup.Application.csproj" />
    <ProjectReference Include="..\Bronnoysund.Lookup.Infrastructure\Bronnoysund.Lookup.Infrastructure.csproj" />
    <ProjectReference Include="..\Bronnoysund.Lookup.Infrastructure.Persistence\Bronnoysund.Lookup.Infrastructure.Persistence.csproj" />
    <ProjectReference Include="..\Bronnoysund.Lookup.Components\Bronnoysund.Lookup.Components.csproj" />
    <ProjectReference Include="..\Bronnoysund.Lookup.ViewModels\Bronnoysund.Lookup.ViewModels.csproj" />
    <ProjectReference Include="..\Bronnoysund.Lookup.Speech\Bronnoysund.Lookup.Speech.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.4.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
