<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Bronnoysund.Application\Bronnoysund.Application.csproj" />
    <ProjectReference Include="..\Bronnoysund.Infrastructure.Brreg.Generated\Bronnoysund.Infrastructure.Brreg.Generated.csproj" />
    <ProjectReference Include="..\Bronnoysund.Infrastructure.Estonia\Bronnoysund.Infrastructure.Estonia.csproj" />
    <ProjectReference Include="..\Bronnoysund.Infrastructure.Finland\Bronnoysund.Infrastructure.Finland.csproj" />
    <ProjectReference Include="..\Bronnoysund.Infrastructure.Ireland\Bronnoysund.Infrastructure.Ireland.csproj" />
    <ProjectReference Include="..\Bronnoysund.Infrastructure.Poland\Bronnoysund.Infrastructure.Poland.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" Version="10.6.0" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.6.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.8" />
    <PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.22.2" />
    <PackageReference Include="Microsoft.Kiota.Http.HttpClientLibrary" Version="1.22.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bronnoysund.Infrastructure.Tests" />
  </ItemGroup>

</Project>
